import { useEffect, useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Clock, Euro, MapPin, Settings, ShieldCheck, Sparkles, Users } from "lucide-react";
import { AdminPanel } from "@/components/AdminPanel";
import { BookingModal } from "@/components/BookingModal";
import { RideCard } from "@/components/RideCard";
import { bookedPlaces, getBlockedDates, getBookings, getRides, saveBlockedDates, saveBookings, saveRides } from "@/lib/storage";
import type { Booking, Ride } from "@/types/booking";

export default function App() {
  const [rides, setRides] = useState<Ride[]>(getRides);
  const [bookings, setBookings] = useState<Booking[]>(getBookings);
  const [blockedDates, setBlockedDates] = useState<string[]>(getBlockedDates);
  const [selectedRide, setSelectedRide] = useState<Ride | null>(null);
  const [adminOpen, setAdminOpen] = useState(false);

  useEffect(() => saveRides(rides), [rides]);
  useEffect(() => saveBookings(bookings), [bookings]);
  useEffect(() => saveBlockedDates(blockedDates), [blockedDates]);

  const available = (ride: Ride) => Math.max(0, ride.capacity - bookedPlaces(ride.id, bookings));
  const nextRides = useMemo(() => [...rides].sort((a,b) => `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)), [rides]);
  const addBooking = (booking: Booking) => setBookings(current => [...current, booking]);
  const addRide = (ride: Ride) => setRides(current => [...current, ride]);
  const toggleRide = (rideId: string) => setRides(current => current.map(ride => ride.id === rideId ? { ...ride, status: ride.status === "blocked" ? "scheduled" : "blocked" } : ride));
  const toggleDate = (date: string) => setBlockedDates(current => current.includes(date) ? current.filter(item => item !== date) : [...current, date]);

  return <main className="min-h-screen overflow-x-hidden bg-stone-50 text-stone-900">
    <header className="sticky top-0 z-30 border-b border-stone-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-3 sm:px-6 sm:py-4"><div className="min-w-0"><p className="truncate text-lg font-bold sm:text-xl">Senda Ecuestre</p><p className="hidden text-xs text-stone-500 sm:block">Experiencias guiadas a caballo</p></div><div className="flex shrink-0 items-center gap-5"><nav className="hidden gap-6 text-sm font-semibold lg:flex"><a href="#salidas">Rutas</a><a href="#experiencia">Experiencia</a><a href="#precios">Precios</a><a href="#ubicacion">Ubicación</a><a href="#seguridad">Seguridad</a></nav><button onClick={()=>setAdminOpen(true)} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-stone-100"><Settings size={17}/> <span className="hidden sm:inline">Administración</span></button></div></div></header>
    <section className="mx-auto grid max-w-6xl gap-8 px-4 py-10 sm:px-6 sm:py-16 lg:grid-cols-[1.2fr_.8fr] lg:items-center lg:gap-10"><div><span className="inline-block rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-800 sm:text-sm">Reserva online · plazas en tiempo real</span><h1 className="mt-5 text-4xl font-bold leading-tight sm:mt-6 sm:text-5xl">Tu próxima aventura empieza a caballo.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-stone-600 sm:text-lg sm:leading-8">Consulta las próximas experiencias ecuestres, comprueba las plazas disponibles y reserva sin llamadas ni esperas.</p><a href="#salidas" className="mt-7 inline-flex w-full justify-center rounded-lg bg-emerald-700 px-5 py-3 font-semibold text-white hover:bg-emerald-800 sm:mt-8 sm:w-auto">Consultar disponibilidad</a></div><div className="rounded-3xl bg-emerald-950 p-6 text-white shadow-xl sm:p-8"><CalendarDays className="h-9 w-9 sm:h-10 sm:w-10"/><h2 className="mt-5 text-2xl font-bold sm:mt-6">Reserva sencilla</h2><div className="mt-5 space-y-4 text-sm text-emerald-50 sm:mt-6 sm:text-base"><p className="flex gap-3"><Clock className="shrink-0"/> Elige fecha y horario</p><p className="flex gap-3"><Users className="shrink-0"/> Comprueba las plazas libres</p><p className="flex gap-3"><ShieldCheck className="shrink-0"/> Confirma tu experiencia</p></div></div></section>
    <section id="salidas" className="bg-white py-12 sm:py-16"><div className="mx-auto max-w-6xl px-4 sm:px-6"><p className="font-bold text-emerald-700">PRÓXIMAS SALIDAS</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><h2 className="text-3xl font-bold">Elige tu experiencia</h2><p className="text-sm text-stone-500">La disponibilidad se actualiza al reservar.</p></div><div className="mt-8 grid gap-6 md:grid-cols-2">{nextRides.map(ride => <RideCard key={ride.id} ride={ride} freePlaces={available(ride)} dateBlocked={blockedDates.includes(ride.date)} onBook={setSelectedRide}/>)}</div></div></section>
    <section id="experiencia" className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16"><p className="font-bold text-emerald-700">LA EXPERIENCIA</p><h2 className="mt-2 max-w-2xl text-3xl font-bold">Rutas pensadas para disfrutar, incluso si nunca has montado</h2><div className="mt-8 grid gap-5 md:grid-cols-3"><Info icon={<Sparkles/>} title="Para todos los niveles">Seleccionamos rutas y caballos según la experiencia del jinete. Las salidas indican claramente el nivel recomendado.</Info><Info icon={<Users/>} title="Grupos reducidos">Los cupos limitados facilitan una atención cercana del guía y una experiencia más tranquila.</Info><Info icon={<ShieldCheck/>} title="Acompañamiento">Antes de salir explicamos manejo básico, posición y normas esenciales de seguridad.</Info></div></section>
    <section id="precios" className="bg-emerald-950 py-12 text-white sm:py-16"><div className="mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 lg:grid-cols-2 lg:items-center"><div><p className="font-bold text-emerald-300">PRECIOS</p><h2 className="mt-2 text-3xl font-bold">Sabes el precio antes de reservar</h2><p className="mt-4 max-w-xl leading-7 text-emerald-50">Cada salida muestra su precio por persona, duración, nivel y plazas disponibles. El importe puede variar según la experiencia elegida.</p></div><div className="rounded-2xl bg-white/10 p-6"><p className="flex items-center gap-3 text-lg font-bold"><Euro/> Información incluida en cada ruta</p><div className="mt-5 grid gap-3 text-sm text-emerald-50 sm:grid-cols-2"><Check>Precio por persona</Check><Check>Duración prevista</Check><Check>Nivel recomendado</Check><Check>Cupo disponible</Check></div></div></div></section>
    <section id="ubicacion" className="mx-auto grid max-w-6xl gap-8 px-4 py-12 sm:px-6 sm:py-16 md:grid-cols-3"><div className="md:col-span-2"><p className="font-bold text-emerald-700">EL CENTRO</p><h2 className="mt-2 text-3xl font-bold">Naturaleza, caballos y rutas guiadas</h2><p className="mt-4 leading-7 text-stone-600">Senda Ecuestre ofrece experiencias para principiantes, familias y jinetes con experiencia. La asignación del caballo se realiza atendiendo al nivel del participante y a las características de la salida.</p><p className="mt-4 text-sm text-stone-500">Esta versión es una demostración funcional: la dirección y los datos comerciales definitivos se incorporarán al adaptar el proyecto a un centro real.</p></div><div className="rounded-2xl border bg-white p-6 shadow-sm"><MapPin className="text-emerald-700"/><h3 className="mt-4 font-bold">Punto de encuentro</h3><p className="mt-2 text-sm leading-6 text-stone-600">Centro Senda Ecuestre · entorno natural y rutas señalizadas. La ubicación exacta se facilitará con la confirmación.</p></div></section>
    <section id="seguridad" className="bg-stone-900 py-12 text-stone-100"><div className="mx-auto max-w-6xl px-4 sm:px-6"><p className="font-bold text-emerald-400">REQUISITOS Y SEGURIDAD</p><h2 className="mt-2 text-2xl font-bold">Antes de montar</h2><div className="mt-6 grid gap-4 text-sm leading-6 text-stone-300 sm:grid-cols-2 lg:grid-cols-4"><Check>Pantalón largo y ropa cómoda</Check><Check>Calzado cerrado y sujeto al pie</Check><Check>Casco obligatorio; el centro puede proporcionarlo</Check><Check>Seguir siempre las indicaciones del guía</Check></div><p className="mt-6 max-w-4xl text-sm leading-6 text-stone-400">Por seguridad y bienestar animal, una ruta o una fecha completa puede aplazarse, modificarse o bloquearse por meteorología, estado del terreno u otras circunstancias que desaconsejen la salida.</p></div></section>
    <footer className="bg-stone-950 py-8 text-stone-400"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-4 text-sm sm:flex-row sm:items-center sm:justify-between sm:px-6"><p><strong className="text-white">Senda Ecuestre</strong> · Demo de reservas ecuestres</p><a href="#salidas" className="font-semibold text-emerald-400">Ver próximas salidas</a></div></footer>
    {selectedRide && <BookingModal ride={selectedRide} freePlaces={available(selectedRide)} onClose={()=>setSelectedRide(null)} onConfirm={addBooking}/>} 
    {adminOpen && <AdminPanel rides={rides} bookings={bookings} blockedDates={blockedDates} onClose={()=>setAdminOpen(false)} onAddRide={addRide} onToggleRide={toggleRide} onToggleDate={toggleDate}/>} 
  </main>;
}

function Info({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) { return <article className="rounded-2xl border bg-white p-6 shadow-sm"><div className="text-emerald-700">{icon}</div><h3 className="mt-4 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-600">{children}</p></article>; }
function Check({ children }: { children: React.ReactNode }) { return <p className="flex items-start gap-2"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-400"/>{children}</p>; }
