import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, Clock, Euro, MapPin, Settings, ShieldCheck, Sparkles, Users } from "lucide-react";
import { AdminPanel } from "@/components/AdminPanel";
import { BookingModal } from "@/components/BookingModal";
import { RideCard } from "@/components/RideCard";
import { bookedPlaces, getBookings, getRides, saveBookings, saveRides } from "@/lib/storage";
import type { Booking, Ride } from "@/types/booking";

export default function App() {
  const [rides, setRides] = useState<Ride[]>(getRides);
  const [bookings, setBookings] = useState<Booking[]>(getBookings);
  const [selectedRide, setSelectedRide] = useState<Ride | null>(null);
  const [adminOpen, setAdminOpen] = useState(false);
  useEffect(() => saveRides(rides), [rides]);
  useEffect(() => saveBookings(bookings), [bookings]);
  const available = (ride: Ride) => Math.max(0, ride.capacity - bookedPlaces(ride.id, bookings));
  const nextRides = useMemo(() => [...rides].sort((a,b) => `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)), [rides]);
  const addBooking = (booking: Booking) => setBookings(current => [...current, booking]);
  const addRide = (ride: Ride) => setRides(current => [...current, ride]);
  const toggleRide = (rideId: string) => setRides(current => current.map(ride => ride.id === rideId ? { ...ride, status: ride.status === "blocked" ? "scheduled" : "blocked" } : ride));

  return <main className="min-h-screen overflow-x-hidden bg-stone-50 text-stone-900">
    <header className="sticky top-0 z-30 border-b border-stone-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-3 sm:px-6 sm:py-4"><div className="min-w-0"><p className="truncate text-lg font-bold sm:text-xl">Senda Ecuestre</p><p className="hidden text-xs text-stone-500 sm:block">Experiencias guiadas a caballo</p></div><div className="flex shrink-0 items-center gap-3 lg:gap-5"><nav className="hidden gap-5 text-sm font-semibold lg:flex"><a href="#salidas">Rutas</a><a href="#precios">Precios</a><a href="#centro">El centro</a><a href="#seguridad">Seguridad</a><a href="#ubicacion">Ubicación</a></nav><button onClick={()=>setAdminOpen(true)} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-stone-100"><Settings size={17}/><span className="hidden md:inline">Administración</span></button></div></div></header>
    <section className="mx-auto grid max-w-6xl gap-8 px-4 py-10 sm:px-6 sm:py-16 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div><span className="inline-block rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-800 sm:text-sm">Reserva online · plazas en tiempo real</span><h1 className="mt-5 text-4xl font-bold leading-tight sm:text-5xl">Tu próxima aventura empieza a caballo.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-stone-600 sm:text-lg sm:leading-8">Consulta las próximas experiencias ecuestres, comprueba las plazas disponibles y reserva sin llamadas ni esperas.</p><a href="#salidas" className="mt-7 inline-flex w-full justify-center rounded-lg bg-emerald-700 px-5 py-3 font-semibold text-white hover:bg-emerald-800 sm:w-auto">Consultar disponibilidad</a></div><div className="rounded-3xl bg-emerald-950 p-6 text-white shadow-xl sm:p-8"><CalendarDays className="h-9 w-9"/><h2 className="mt-5 text-2xl font-bold">Reserva sencilla</h2><div className="mt-5 space-y-4 text-sm text-emerald-50 sm:text-base"><p className="flex gap-3"><Clock className="shrink-0"/> Elige fecha y horario</p><p className="flex gap-3"><Users className="shrink-0"/> Comprueba las plazas libres</p><p className="flex gap-3"><ShieldCheck className="shrink-0"/> Confirma tu experiencia</p></div></div></section>
    <section id="salidas" className="bg-white py-12 sm:py-16"><div className="mx-auto max-w-6xl px-4 sm:px-6"><p className="font-bold text-emerald-700">PRÓXIMAS SALIDAS</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><h2 className="text-3xl font-bold">Elige tu experiencia</h2><p className="text-sm text-stone-500">La disponibilidad se actualiza al reservar.</p></div><div className="mt-8 grid gap-6 md:grid-cols-2">{nextRides.map(ride => <RideCard key={ride.id} ride={ride} freePlaces={available(ride)} onBook={setSelectedRide}/>)}</div></div></section>
    <section id="precios" className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16"><div className="max-w-2xl"><p className="font-bold text-emerald-700">EXPERIENCIAS Y PRECIOS</p><h2 className="mt-2 text-3xl font-bold">Una ruta para cada jinete</h2><p className="mt-4 text-stone-600">Los precios mostrados son orientativos y cada salida publicada indica su precio definitivo.</p></div><div className="mt-8 grid gap-5 md:grid-cols-3">{[["Iniciación","Desde 25 €","Primera toma de contacto, explicación básica y paseo tranquilo."],["Ruta naturaleza","Desde 35 €","Recorrido guiado por caminos y entorno natural para disfrutar del paisaje."],["Experiencia avanzada","Desde 45 €","Salidas para jinetes con experiencia previa y mayor autonomía."]].map(([title,price,text])=><article key={title} className="rounded-2xl border bg-white p-6 shadow-sm"><Euro className="text-emerald-700"/><h3 className="mt-4 text-xl font-bold">{title}</h3><p className="mt-2 font-bold text-emerald-700">{price}</p><p className="mt-3 text-sm leading-6 text-stone-600">{text}</p></article>)}</div></section>
    <section id="centro" className="bg-white py-12 sm:py-16"><div className="mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 md:grid-cols-3"><div className="md:col-span-2"><p className="font-bold text-emerald-700">SENDA ECUESTRE</p><h2 className="mt-2 text-3xl font-bold">Rutas para disfrutar con seguridad</h2><p className="mt-4 leading-7 text-stone-600">Experiencias guiadas para principiantes, familias y jinetes con experiencia. Antes de cada salida asignamos el caballo adecuado y realizamos una breve explicación de manejo y seguridad.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><p className="flex gap-2 text-sm"><Check className="shrink-0 text-emerald-700" size={19}/> Grupos reducidos y cupos controlados.</p><p className="flex gap-2 text-sm"><Check className="shrink-0 text-emerald-700" size={19}/> Caballo adaptado al nivel del jinete.</p><p className="flex gap-2 text-sm"><Check className="shrink-0 text-emerald-700" size={19}/> Guía durante toda la experiencia.</p><p className="flex gap-2 text-sm"><Check className="shrink-0 text-emerald-700" size={19}/> Casco disponible en el centro.</p></div></div><div className="rounded-2xl bg-emerald-50 p-6"><Sparkles className="text-emerald-700"/><h3 className="mt-4 font-bold">¿Es tu primera vez?</h3><p className="mt-2 text-sm leading-6 text-stone-600">No necesitas experiencia para las rutas marcadas como iniciación. Indica tu nivel al reservar para preparar la salida.</p></div></div></section>
    <section id="seguridad" className="bg-stone-900 py-12 text-stone-100 sm:py-16"><div className="mx-auto max-w-6xl px-4 sm:px-6"><p className="font-bold text-emerald-400">REQUISITOS Y NORMAS</p><h2 className="mt-2 text-3xl font-bold">Antes de montar</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["Pantalón largo y ropa cómoda.","Calzado cerrado y sujeto al pie.","Casco obligatorio durante la actividad.","Sigue siempre las indicaciones del guía."].map(rule=><div key={rule} className="rounded-xl border border-stone-700 bg-stone-800 p-4 text-sm leading-6"><ShieldCheck className="mb-3 text-emerald-400"/>{rule}</div>)}</div><p className="mt-6 max-w-3xl text-sm leading-6 text-stone-300">Por seguridad y bienestar de caballos y participantes, una salida puede aplazarse o bloquearse por meteorología, estado del terreno u otras circunstancias. El centro confirmará cualquier cambio.</p></div></section>
    <section id="ubicacion" className="mx-auto grid max-w-6xl gap-6 px-4 py-12 sm:px-6 sm:py-16 md:grid-cols-2"><div><p className="font-bold text-emerald-700">UBICACIÓN</p><h2 className="mt-2 text-3xl font-bold">Punto de encuentro</h2><p className="mt-4 leading-7 text-stone-600">Centro Senda Ecuestre · entorno natural y rutas señalizadas. Preséntate 15 minutos antes de la hora de salida para preparar el equipo y recibir las indicaciones previas.</p></div><div className="rounded-2xl border bg-white p-6"><MapPin className="text-emerald-700"/><h3 className="mt-4 font-bold">Antes de venir</h3><p className="mt-2 text-sm leading-6 text-stone-600">La dirección exacta y las indicaciones de acceso pueden facilitarse junto con la confirmación de la reserva. Para grupos o necesidades especiales, consulta previamente con el centro.</p></div></section>
    <footer className="border-t bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-4 py-8 text-sm text-stone-500 sm:px-6 md:flex-row md:items-center md:justify-between"><p><strong className="text-stone-800">Senda Ecuestre</strong> · Experiencias guiadas a caballo</p><a href="#salidas" className="font-semibold text-emerald-700">Ver próximas salidas</a></div></footer>
    {selectedRide && <BookingModal ride={selectedRide} freePlaces={available(selectedRide)} onClose={()=>setSelectedRide(null)} onConfirm={addBooking}/>} 
    {adminOpen && <AdminPanel rides={rides} bookings={bookings} onClose={()=>setAdminOpen(false)} onAddRide={addRide} onToggleRide={toggleRide}/>} 
  </main>;
}
